version: '3'
services:
  redis:
    image: redis:4.0.11
    ports:
      - 6379
    command: ["redis-server","--requirepass","root"]
  sip-eureka:
    image: registry.cn-beijing.aliyuncs.com/basicfu/sip-eureka:master-156
    environment:
      - ENV=prod
    ports:
      - "7000:80"
  sip-getway:
    image: registry.cn-beijing.aliyuncs.com/basicfu/sip-getway:master-156
    depends_on:
      - sip-eureka
    environment:
      - ENV=prod
      - ENV_EUREKA_HOST=sip-eureka
      - ENV_EUREKA_PORT=80
      - ENV_MYSQL_HOST=mysql-dev.dmka.cn
      - ENV_MYSQL_PORT=4321
      - ENV_MYSQL_USERNAME=root
      - ENV_MYSQL_PASSWORD=root
      - ENV_REDIS_HOST=redis
      - ENV_REDIS_PORT=6379
      - ENV_REDIS_PASSWORD=root
    ports:
      - "7100:80"
  sip-base:
    image: registry.cn-beijing.aliyuncs.com/basicfu/sip-base:master-156
    depends_on:
      - sip-eureka
    environment:
      - ENV=prod
      - ENV_EUREKA_HOST=sip-eureka
      - ENV_EUREKA_PORT=80
      - ENV_MYSQL_HOST=mysql-dev.dmka.cn
      - ENV_MYSQL_PORT=4321
      - ENV_MYSQL_USERNAME=root
      - ENV_MYSQL_PASSWORD=root
      - ENV_REDIS_HOST=redis
      - ENV_REDIS_PORT=6379
      - ENV_REDIS_PASSWORD=root
