version: '3'
services:
  redis:
    image: redis:4.0.11
    ports:
      - 6379:6379
    command: ["redis-server","--requirepass","root"]
    network_mode: "host"
  sip-eureka:
    image: registry.cn-beijing.aliyuncs.com/basicfu/sip-eureka
    environment:
      - ENV=dev
      - ENV_SERVER_PORT=7000
    ports:
      - "7000:7000"
    network_mode: "host"
  sip-getway:
    image: registry.cn-beijing.aliyuncs.com/basicfu/sip-getway
    depends_on:
      - sip-eureka
    environment:
      - ENV=dev
      - ENV_SERVER_PORT=7100
      - ENV_EUREKA_HOST=localhost
      - ENV_EUREKA_PORT=7000
      - ENV_MYSQL_HOST=mysql.czkj.cn
      - ENV_MYSQL_PORT=5306
      - ENV_MYSQL_USERNAME=root
      - ENV_MYSQL_PASSWORD=czkjroot
      - ENV_REDIS_HOST=localhost
      - ENV_REDIS_PORT=6379
      - ENV_REDIS_PASSWORD=root
    ports:
      - "7100:7100"
    network_mode: "host"
  sip-base:
    image: registry.cn-beijing.aliyuncs.com/basicfu/sip-base
    depends_on:
      - sip-eureka
    environment:
      - ENV=dev
      - ENV_SERVER_PORT=7200
      - ENV_EUREKA_HOST=localhost
      - ENV_EUREKA_PORT=7000
      - ENV_MYSQL_HOST=mysql.czkj.cn
      - ENV_MYSQL_PORT=5306
      - ENV_MYSQL_USERNAME=root
      - ENV_MYSQL_PASSWORD=czkjroot
      - ENV_REDIS_HOST=localhost
      - ENV_REDIS_PORT=6379
      - ENV_REDIS_PASSWORD=root
    ports:
      - "7200:7200"
    network_mode: "host"
