version: '3'
services:
  sip-eureka:
    image: registry.cn-beijing.aliyuncs.com/basicfu/sip-eureka
    environment:
      - ENV=prod
    ports:
      - "7000:80"
  sip-getway:
    image: registry.cn-beijing.aliyuncs.com/basicfu/sip-getway
    depends_on:
      - sip-eureka
    environment:
      - ENV=prod
      - ENV_EUREKA_HOST=sip-eureka
      - ENV_EUREKA_PORT=80
    ports:
      - "7100:80"