#指定数据库下不需要使用app_id的表
sip:
  app-field: app_id
  app-exclude-table:
    sip-base:
      - app
    sip-permission:
      - user_role
      - menu_resource
      - permission_resource
      - role_menu
      - role_permission
      - user_role
      - resource
    sip-tools:
      - kube_charts
